name: Static Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Yarn
        run: yarn

      - name: TypeScript
        run: yarn tsc

      - name: ESLint
        run: yarn lint
